### ISSUE TITLE
Request: Report separated video and audio url

### ISSUE THREAD

**Issue by xingrz** [charlieMonroe/DownieCustomIntegrations#1]
Some sites (e.g. https://www.bilibili.tv/en/play/1022690/) serves video track and audio track separately. It would be great if a custom integration can report a pair of separated video and audio URLs and let Downie to do the merging job.

**Comment by charlieMonroe** [comment]
@xingrz Please request this via the in-app support dialog using the Support button in the bottom-right corner of the main window.

I cannot track issues on multiple channels. Thank you for understanding.
